# Use root/example as user/password credentials
version: '3.1'

networks:
  database-net:
    driver: bridge

services:

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - database-net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 7720:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/
    networks:
      - database-net



